version: '3.8'

services:
  web_service:
    container_name: telua_python_flask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    stdin_open: true
    tty: true
